name: Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          check-latest: true

      - name: Install dependencies
        run: |
          go install 4d63.com/vangen@latest

      - name: Set git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Generate + Push
        run: |
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git checkout public
          git pull origin public
          git restore --source main vangen.json
          vangen -out .
          git add .
          git commit -m "Update generated files"
          git push
